import { CreativeFormData } from '@/types';

export function generateCreativePrompt(data: CreativeFormData): string {
  const sections: string[] = [];

  // Header
  sections.push(`# Creative Writing Prompt: ${data.genre} ${data.format}\n\n`);
  sections.push('---\n\n');

  // Overview
  sections.push('## Story Overview\n\n');
  sections.push('| Element | Details |\n');
  sections.push('|---------|----------|\n');
  sections.push(`| **Genre** | ${data.genre || 'Not specified'} |\n`);
  sections.push(`| **Format** | ${data.format || 'Not specified'} |\n`);
  sections.push(`| **Length** | ${data.length || 'Not specified'} |\n`);
  sections.push(`| **Tone** | ${data.tone || 'Not specified'} |\n`);
  sections.push(`| **POV** | ${data.perspective || 'Not specified'} |\n`);
  if (data.theme) {
    sections.push(`| **Theme** | ${data.theme} |\n`);
  }
  sections.push('\n');

  // Setting
  if (data.setting) {
    sections.push('## Setting & World\n\n');
    sections.push(data.setting);
    sections.push('\n\n');
  }

  // Characters
  if (data.characters) {
    sections.push('## Characters\n\n');
    sections.push(data.characters);
    sections.push('\n\n');
  }

  // Plot Elements
  if (data.plotElements) {
    sections.push('## Plot Elements\n\n');
    sections.push(data.plotElements);
    sections.push('\n\n');
  }

  // Style
  if (data.style) {
    sections.push('## Writing Style\n\n');
    sections.push(`Style: ${data.style}\n\n`);
  }

  // Inspiration
  if (data.inspiration) {
    sections.push('## Inspiration/Reference\n\n');
    sections.push(data.inspiration);
    sections.push('\n\n');
  }

  // Constraints
  if (data.constraints) {
    sections.push('## Special Requirements\n\n');
    sections.push(data.constraints);
    sections.push('\n\n');
  }

  // Ready-to-use prompt
  sections.push('---\n\n');
  sections.push('## Ready-to-Use Prompt\n\n');
  sections.push('Copy this prompt to use with ChatGPT, Claude, or any AI:\n\n');
  sections.push('```\n');

  let copyPrompt = `Write a ${data.format || 'story'}`;
  if (data.length) {
    copyPrompt += ` (${data.length})`;
  }
  copyPrompt += ` in the ${data.genre || 'fiction'} genre`;
  if (data.tone) {
    copyPrompt += ` with a ${data.tone} tone`;
  }
  copyPrompt += '.\n\n';

  if (data.perspective) {
    copyPrompt += `Point of View: ${data.perspective}\n`;
  }

  if (data.theme) {
    copyPrompt += `Theme: ${data.theme}\n`;
  }

  if (data.setting) {
    copyPrompt += `\nSetting:\n${data.setting}\n`;
  }

  if (data.characters) {
    copyPrompt += `\nCharacters:\n${data.characters}\n`;
  }

  if (data.plotElements) {
    copyPrompt += `\nPlot Elements:\n${data.plotElements}\n`;
  }

  if (data.style) {
    copyPrompt += `\nWriting Style: ${data.style}\n`;
  }

  if (data.inspiration) {
    copyPrompt += `\nInspiration: ${data.inspiration}\n`;
  }

  if (data.constraints) {
    copyPrompt += `\nRequirements: ${data.constraints}\n`;
  }

  copyPrompt += '\nCreate an engaging, well-crafted piece with vivid descriptions, compelling characters, and a satisfying narrative arc.';

  sections.push(copyPrompt);
  sections.push('\n```\n\n');

  // Variations
  sections.push('## Prompt Variations\n\n');

  sections.push('### Opening Line Prompt\n');
  sections.push('```\n');
  sections.push(`Write an engaging opening line for a ${data.genre || 'fiction'} ${data.format || 'story'}${data.setting ? ` set in ${data.setting.split('.')[0]}` : ''}${data.tone ? ` with a ${data.tone} tone` : ''}.\n`);
  sections.push('```\n\n');

  sections.push('### Character Development Prompt\n');
  sections.push('```\n');
  sections.push(`Develop detailed character profiles for a ${data.genre || 'fiction'} story${data.theme ? ` exploring the theme of "${data.theme}"` : ''}. Include their motivations, flaws, and character arc.\n`);
  sections.push('```\n\n');

  sections.push('### Scene Writing Prompt\n');
  sections.push('```\n');
  sections.push(`Write a pivotal scene for a ${data.genre || 'fiction'} ${data.format || 'story'}${data.tone ? ` with a ${data.tone} atmosphere` : ''}${data.characters ? ` featuring the characters described` : ''}.\n`);
  sections.push('```\n\n');

  // Tips
  sections.push('## Writing Tips\n\n');
  sections.push('1. **Show, Don\'t Tell**: Use sensory details and action to convey emotions\n');
  sections.push('2. **Start In Media Res**: Begin in the middle of the action\n');
  sections.push('3. **Create Conflict**: Every scene should have tension or stakes\n');
  sections.push('4. **Develop Voice**: Make your narrator distinct and consistent\n');
  sections.push('5. **End with Impact**: Leave readers thinking or feeling something\n\n');

  // Footer
  sections.push('---\n');
  sections.push('*Generated by AI Prompter - https://github.com/Saqibnawazkhan/AI-Prompter*\n');

  return sections.join('');
}
