import { ImageFormData } from '@/types';

export function generateImagePrompt(data: ImageFormData): string {
  const sections: string[] = [];

  // Main prompt
  sections.push('# Image Generation Prompt\n\n');
  sections.push('---\n\n');

  // Primary Prompt Section
  sections.push('## Main Prompt\n\n');

  // Build the optimized prompt
  const promptParts: string[] = [];

  // Subject (most important)
  if (data.subject) {
    promptParts.push(data.subject);
  }

  // Style
  if (data.style) {
    promptParts.push(`${data.style} style`);
  }

  // Mood
  if (data.mood) {
    promptParts.push(`${data.mood} atmosphere`);
  }

  // Lighting
  if (data.lighting) {
    promptParts.push(data.lighting);
  }

  // Color palette
  if (data.colorPalette) {
    promptParts.push(`${data.colorPalette} color palette`);
  }

  // Composition
  if (data.composition) {
    promptParts.push(data.composition);
  }

  // Perspective
  if (data.perspective) {
    promptParts.push(`${data.perspective} angle`);
  }

  // Background
  if (data.background) {
    promptParts.push(`${data.background} background`);
  }

  // Details
  if (data.details) {
    promptParts.push(data.details);
  }

  // Artistic reference
  if (data.artisticReference) {
    promptParts.push(data.artisticReference);
  }

  // Quality
  if (data.quality) {
    promptParts.push(data.quality);
  }

  // Format the main prompt
  sections.push('```\n');
  sections.push(promptParts.join(', '));
  sections.push('\n```\n\n');

  // Detailed breakdown
  sections.push('## Prompt Breakdown\n\n');
  sections.push('| Element | Value |\n');
  sections.push('|---------|-------|\n');
  sections.push(`| **Subject** | ${data.subject || 'Not specified'} |\n`);
  sections.push(`| **Style** | ${data.style || 'Not specified'} |\n`);
  sections.push(`| **Mood** | ${data.mood || 'Not specified'} |\n`);
  sections.push(`| **Lighting** | ${data.lighting || 'Not specified'} |\n`);
  sections.push(`| **Colors** | ${data.colorPalette || 'Not specified'} |\n`);
  sections.push(`| **Composition** | ${data.composition || 'Not specified'} |\n`);
  sections.push(`| **Perspective** | ${data.perspective || 'Not specified'} |\n`);
  sections.push(`| **Background** | ${data.background || 'Not specified'} |\n`);
  sections.push(`| **Quality** | ${data.quality || 'Not specified'} |\n`);
  sections.push(`| **Aspect Ratio** | ${data.aspectRatio || 'Not specified'} |\n`);
  sections.push('\n');

  // Negative prompts
  if (data.negativePrompts) {
    sections.push('## Negative Prompt\n\n');
    sections.push('Things to avoid in the generation:\n\n');
    sections.push('```\n');
    sections.push(data.negativePrompts);
    sections.push('\n```\n\n');
  }

  // Platform-specific prompts
  sections.push('## Platform-Specific Versions\n\n');

  // Midjourney
  sections.push('### Midjourney\n\n');
  sections.push('```\n');
  let mjPrompt = promptParts.join(', ');
  if (data.aspectRatio) {
    const arMap: Record<string, string> = {
      '1:1 (Square)': '--ar 1:1',
      '16:9 (Widescreen)': '--ar 16:9',
      '9:16 (Portrait)': '--ar 9:16',
      '4:3 (Standard)': '--ar 4:3',
      '3:2 (Photo)': '--ar 3:2',
      '21:9 (Cinematic)': '--ar 21:9',
    };
    mjPrompt += ` ${arMap[data.aspectRatio] || '--ar 1:1'}`;
  }
  mjPrompt += ' --v 6';
  sections.push(mjPrompt);
  sections.push('\n```\n\n');

  // DALL-E
  sections.push('### DALL-E 3\n\n');
  sections.push('```\n');
  sections.push(promptParts.join(', '));
  sections.push('\n```\n\n');

  // Stable Diffusion
  sections.push('### Stable Diffusion\n\n');
  sections.push('**Positive Prompt:**\n');
  sections.push('```\n');
  let sdPrompt = promptParts.join(', ');
  sdPrompt += ', highly detailed, sharp focus, professional';
  sections.push(sdPrompt);
  sections.push('\n```\n\n');

  if (data.negativePrompts) {
    sections.push('**Negative Prompt:**\n');
    sections.push('```\n');
    sections.push(data.negativePrompts + ', blurry, low quality, distorted, deformed');
    sections.push('\n```\n\n');
  }

  // Tips
  sections.push('## Tips for Best Results\n\n');
  sections.push('1. **Be Specific**: The more detailed your description, the better the result\n');
  sections.push('2. **Order Matters**: Put the most important elements first\n');
  sections.push('3. **Experiment**: Try different styles and lighting combinations\n');
  sections.push('4. **Iterate**: Generate multiple versions and refine based on results\n');
  sections.push('5. **Use References**: Artistic references can dramatically improve output\n\n');

  // Footer
  sections.push('---\n');
  sections.push('*Generated by AI Prompter - https://github.com/Saqibnawazkhan/AI-Prompter*\n');

  return sections.join('');
}
